blog/article_app/urls.py
from django.urls import path, include

from article_app.views import Articles, CreateArticleView, DeleteArticleView, EditArticleView, ReadArticleView

app_name = 'article_app'

urlpatterns = [
    path('', include([
   	    path('articles/', Articles.as_view(), name='articles_url'),
        path('create/', CreateArticleView.as_view(), name='create_url'),
        path('read/', ReadArticleView.as_view(), name='read_article_url'),
        path('edit/<int:pk>', EditArticleView.as_view(), name='edit_article_url'),
        path('delete/<int:pk>', DeleteArticleView.as_view(), name='delete_article_url'),
    ]))
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home_app.urls')),
    path('article/', include('article_app.urls')),
    path('users/', include('user_app.urls')),

    path('admin/', admin.site.urls),
]

blog/article_app/models/article_models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

from user_app.models import CustomUser
from article_app.models.category_models import Category


class Article(models.Model):

    class Meta:
        verbose_name = u'Article'
        verbose_name_plural = u'Articles'

    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT)

    title = models.CharField(
        max_length=70,
        blank=False,
        verbose_name=u"Article title")

    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=u'Article category')

    content = models.CharField(
        max_length=10000,
        blank=False,
        verbose_name=u'Article content')

    created_on = models.DateField(
        auto_now_add=True,
        verbose_name=u'Date of add of Article')

    def get_articles_filtered_by_category(self, read_category):
        try:
            articles = Article.objects.filter(category=read_category)
        except Article.DoesNotExist:
            articles = None
        return articles

    def get_articles_filtered_by_author(self, read_author):
        try:
            articles = Article.objects.filter(author=read_author)
        except Article.DoesNotExist:
            articles = None
        return articles

    def get_selected_articles_by_pk(self, pk):
        try:
            articles = Article.objects.filter(pk=pk)
        except Article.DoesNotExist:
            articles = None
        return articles

    def get_all_articles(self):
        return Article.objects.all()

    def __str__(self):
        return '%s %s %s %s %s' % (self.author, self.title, self.category, self.content, self.created_on)

blog/article_app/models/category_models.py
# -*- coding: utf-8 -*-
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name = u'Article Category'
        verbose_name_plural = u'Article Categories'

    category_name = models.CharField(
        max_length=20,
        blank=False,
        verbose_name=u'Category Name')

    def get_all_categories(self):
        return Category.objects.all()

    def __str__(self):
        return '%s' % self.category_name

blog/article_app/forms.py
from django import forms

from article_app.models.article_models import Article


class CreateArticleForm(forms.ModelForm):

	class Meta:
		model = Article
		fields = ('title', 'category', 'content')

	category = forms.Select()
	content = forms.CharField(max_length=2560, widget=forms.Textarea())

blog/article_app/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView, View
#from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User

from blog.util import get_read_selected_category, get_read_selected_author#, get_selected_articles
from article_app.forms import CreateArticleForm
from article_app.models import Article, Category
from home_app.permissions import NeedLogin
from user_app.models import CustomUser


class Articles(View):

    def get(self, request):
        read_category = get_read_selected_category(request)
        read_author = get_read_selected_author(request)

        authors = User.objects.all()
        #authors = CustomUser.get_all_authors(self)
        categories = Category.get_all_categories(self)

        if read_category:
            articles = Article.get_articles_filtered_by_category(self, read_category)[::-1]
        elif read_author:
            articles = Article.get_articles_filtered_by_author(self, read_author)[::-1]
        else:
            articles = Article.get_all_articles(self)[::-1]

        return render(request, 'article_app/article.html', {
            'authors': authors, 'categories': categories, 'articles': articles})



class CreateArticleView(NeedLogin, View):
	"""CBV for writing new article"""

	model = Article
	form_class = CreateArticleForm
	template_name = 'article_app/create_article.html'

	def get(self, request, *args, **kwargs):
		form = CreateArticleForm()
		categories = Category.get_all_categories(self)
		return render(request, 'article_app/create_article.html', {'form': form, 'categories': categories})

	def post(self, request, *args, **kwargs):
		form = CreateArticleForm(data=request.POST)

		if form.is_valid():

			new_article = form.save(commit=False)
			new_article.author = CustomUser.get_current_user(self, request)
			new_article.save()
			return HttpResponseRedirect('%s?status_message=%s' %(reverse('article_app:create_url'), 'New article added!'))


class ReadArticleView(TemplateView):

	def get(self, request, *args, **kwargs):
		#selected_art_info = get_selected_articles(request)
		# selected_article = Article.objects.filter(title=selected_art_info.title)
		pk = request.COOKIES.get('selected_article_read')
		selected_article = Article.get_selected_articles_by_pk(self, pk)
		
		return render(request, 'article_app/read_article.html', {'selected_article': selected_article})


class EditArticleView(NeedLogin, UpdateView):
	model = Article
	form_class = CreateArticleForm
	#fields = ['title', 'content', 'category']
	template_name = 'article_app/edit_article.html'

	def get_success_url(self):
		return '%s?status_message=Article Edited!' %(reverse('article_app:read_article_url'))

	def post(self, request, *args, **kwargs):
		return super(EditArticleView, self).post(request, *args, **kwargs)

	# @method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(EditArticleView, self).dispatch(*args, **kwargs)


class DeleteArticleView(NeedLogin, DeleteView):
	model = Article
	template_name = 'article_app/delete_article.html'

	def get_success_url(self):
		return '%s?status_message=Article Deleted!' %(reverse('home_app:home_url'))

	def post(self, request, *args, **kwargs):
		return super(DeleteArticleView, self).post(request, *args, **kwargs)

	# @method_decorator(login_required)
	# def dispatch(self, *args, **kwargs):
	# 	return super(DeleteArticleView, self).dispatch(*args, **kwargs)

blog/templates/article_app/article.html
{% extends 'home_app/base.html' %}

{% block title %}Article page{% endblock %}

{% block content %}

	<div class="container">

		<div class="row">
			<hr>

			<div class="col-md-4" id='category_selector_read'>
				<button id='read_button'>Show All Stories</button>
				<p>Filter by <select name="" id="category_selector"><br>

						<option class="category_option">categories</option>

						{% for category in categories %}
							<option value="{{ category.id }}">
								{{ category.category_name }}
							</option>
						{% endfor %}

					</select>
					<br>
					or <br><select name="" id="author_selector">

						<option value="">authors</option>

						{% for author in authors %}
							<option value="{{ author.id }}">
								{{ author.first_name }} {{ author.last_name }}
							</option>
						{% endfor %}

					</select>
				</p>
			</div> <!-- end category_selector div -->

			<div class="col-md-8" id="articles_info">

				{% if articles %}
					{% for entry in articles %}
						<div class="col-md-6 text-center home_article_div">
								
									<h4><span class="article_title">{{ entry.title }}</span></h4>
									<p><span class="article_category_style">{{ entry.category }}</span></p>
									<p>created by <span class="author_style">{{ entry.author.first_name }} {{ entry.author.last_name }}</span></p>
									<p><span class="date_style">{{ entry.created_on }}</span></p>
									<a href="{% url 'article_app:read_article_url' %}" 
										class="a_btn" id="read_full_article">Read more
										<input type="hidden" value="{{entry.pk}}">
									</a>
								
							<hr>
						</div>
					{% endfor %}
				{% else %}

					<p>No article by this filter!</p>

				{% endif %}




			</div> <!-- end div.articles -->

		</div> <!-- end row -->

	</div> <!-- end container -->


{% endblock content %}

blog/templates/article_app/create_article.html
{% extends 'home_app/base.html' %}

{% block title %}Create new article{% endblock %}
{% block content %}

	<div class="row">

		<div class="col-xs-12 col-md-6 col-md-offset-3 create_article_div">
			<hr>
			
			<form action="{% url 'article_app:create_url' %}"
					method="post"
					role='form'
					name='create_form'>
				{% csrf_token %}

				<div class="category_selector_create">
					<select name="category" id="">

							{% for category in categories %}
								<option value="{{ category.id }}">
									{{ category.category_name }}
								</option>
							{% endfor %}

					</select>
				</div>

						<input type="text"
								name='title'
								value="{{ request.POST.title }}"placeholder="Article title"
								required
								autofocus
								>
				
						<textarea class='article_content'
								name="content"
								placeholder="Article content" 
								id="article_content"
								cols="60" rows="5"
								value='{{ request.POST.content }}'
								required></textarea>
					
				<div class="col-xs-12 col-md-1 col-md-offset-11">
					<button id="create_article_button" type="submit" name='send_button'>Create</button>
				</div>

			</form>

		</div> <!-- end form div -->

	</div> <!-- end row -->

{% endblock content %}

blog/templates/article_app/delete_article.html
{% extends 'home_app/base.html' %}

{% block title %}Deleting article{% endblock %}
{% block content %}
	<div class="row">
		<div class="col-xs-12 col-md-6 col-md-offset-3 text-center">
			<hr>
			<form method='post'>
				{% csrf_token %}
				<h3>Are you sure you want delete this article?</h3>
				{{ form.as_p }}
				
				<div class="col-xs-12 col-md-7 col-md-offset-4 text-right">
					<button type="submit" class='delete_button'>Delete</button>
					<a href="{% url 'article_app:read_article_url' %}" class="cancel_button">Cancel</a>
				</div>

			</form>
		</div>
	</div>

{% endblock content %}

blog/templates/article_app/edit_article.html
{% extends 'home_app/base.html' %}

{% block title %}Updating current article{% endblock %}
{% block content %}

	<div class="row">
		<hr>
		<div class="col-xs-12 text-center">
			<form method='post'>
				{% csrf_token %}
				{{ form.as_p }}
				
				<div class="col-xs-12 col-md-7 col-md-offset-1 text-right">
					<button type="submit" name='Update'>Update</button>
					<a href="{% url 'article_app:read_article_url' %}">Cancel</a>
				</div>
				
			</form>
		</div>
	</div>

{% endblock content %}

blog/templates/article_app/read_article.html
{% extends 'home_app/base.html' %}

{% block content %}

	<div class="row">

		{% for entry in selected_article %}
		<div class="row">
			<div class="col-xs-12 col-md-2 col-md-offset-5 text-center">
				<h4><span class="article_title">{{ entry.title }}</span></h4>
			</div>
			<div class="col-xs-12 col-md-3 col-md-offset-1 author_info">
				<p>by<span class="author_style">{{ entry.author.first_name }} {{ entry.author.last_name }}</span>, <span class="date_style">{{ entry.created_on }}</span> </p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-md-offset-3 text-center">
				<hr>
				<article>{{ entry.content }} </article>
				<hr>

				{% ifequal entry.author request.user %}
					<div class="col-xs-12 col-md-7 col-md-offset-5 text-right">
						<a href="{% url 'article_app:edit_article_url' pk=entry.id %}">
							<button>Edit Article</button>
						</a>

						<a href="{% url 'article_app:delete_article_url' pk=entry.id %}">
							<button class='delete_button'>Delete Article</button>
						</a>
					</div>
				
				{% endifequal %}

			</div>
		</div>

		{% endfor %}

	</div> <!-- end row -->

{% endblock content %}