blog/article_app/urls.py
from django.urls import path, include

from article_app.views import Articles, CreateArticleView, DeleteArticleView, EditArticleView, ReadArticleView

app_name = 'article_app'

urlpatterns = [
    path('', include([
   	    path('articles/', Articles.as_view(), name='articles_url'),
        path('create/', CreateArticleView.as_view(), name='create_url'),
        path('read/', ReadArticleView.as_view(), name='read_article_url'),
        path('edit/<int:pk>', EditArticleView.as_view(), name='edit_article_url'),
        path('delete/<int:pk>', DeleteArticleView.as_view(), name='delete_article_url'),
    ]))
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home_app.urls')),
    path('article/', include('article_app.urls')),
    path('users/', include('user_app.urls')),

    path('admin/', admin.site.urls),
]

blog/home_app/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'home_app'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home_app/home.html'), name='home_url')
]

blog/user_app/urls.py
from django.urls import path

from user_app.views import AuthorListView, LoginView, LogoutView, UpdateUserView, SignUpView

app_name = 'user_app'

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='authors_url'),
    path('login/', LoginView.as_view(), name='login_url'),
    path('logout/', LogoutView.as_view(), name='logout_url'),
    path('update/<int:pk>', UpdateUserView.as_view(), name='update_url'),
    path('signup/', SignUpView.as_view(), name='signup_url'),

]

blog/templates/home_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Blog</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<header>
	<ul>
        <li>
            <a href="{% url 'home_app:home_url' %}" class='menu__linl'>Home
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        <li>
            <a href="{% url 'article_app:articles_url' %}" class='menu__linl'>Articles
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_app:authors_url' %}" class='menu__linl'>Authors
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'article_app:create_url' %}" class='menu__linl'>Create
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_app:update_url' pk=user.pk %}" class='menu__linl'> 
            		<!-- {% if user.first_name %}
            			{{ user.first_name }} {{ user.last_name }}
                        
            		{% else %}
            			{{ user.username }}
                        
            		{% endif %} -->
                                            {{ user.username }}

                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_app:logout_url' %}" class='menu__linl'>Logout
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'user_app:signup_url' %}" class='menu__linl'>Registration
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_app:login_url' %}" class='menu__linl'>Login
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </li>
        {% endif %}
    </ul>

    <hr style='position: relative; top:20px; border-top: 1px solid white;'>


</header>

<div class="row">

<div class="col-xs-12 col-md-6 col-md-offset-3 text-center title_div">
	<h2>{% block title %}{% endblock %}</h2>			
</div>

<div class="col-xs-12 col-md-4 col-md-offset-4 text-center">
	{% block status_message %}
		{% if request.GET.status_message %}
			<div class="alert alert-warning status_message" role="alert">{{ request.GET.status_message }}
			</div>
		{% endif %}
	{% endblock %}
</div>

<div class="container">
{% block content %}
{% endblock content %}
</div>

<footer>

<div class="row">

	<div class="col-xs-12 col-md-2 col-md-offset-1">
		<p>&copy; 2019 <span>Blog</span></p>
	</div>
    

	<div class="col-xs-12 col-md-2 col-md-offset-4"><p>
		 Produced by <span style="font-family: 'Pacifico'; font-style: italic">Vasyl Pyrih</span></p>
	</div>

    <div class="col-xs-12 col-md-1">
        <a href=https://github.com/Pyrigok/blog>Github</a>
    </div>
    <div class="col-xs-12 col-md-1">
        <a href="https://www.linkedin.com/in/vasyl-pyrig-5610b0138/">LinkedIn</a>
    </div>
</div>

</footer>

<!-- jquery -->
<script
src="https://code.jquery.com/jquery-2.2.4.js"
integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
crossorigin="anonymous"></script>

<!-- jQuery Cookie -->
<script src="{% static 'scripts/jquery.cookie.js' %}"></script>
<!--<script src="../../static/scripts/jquery.cookie.js"></script>-->

<!-- bootstrap js -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- our custom cookies -->
<script src="{% static 'scripts/cookie.js' %}"></script>
<!--<script src="../../static/scripts/cookie.js"></script>-->

</body>
</html>

blog/templates/home_app/home.html
{% extends 'home_app/base.html' %}

{% block content %}
	
	<div class="row">

		<div class="col-xs-12 col-md-6 col-md-offset-3 welcome_div text-center">
			<h2>Welcome</h2>
			<hr>
			<p>Here you can <a href="{% url 'article_app:articles_url' %}">read</a> some stories and write your own stories after <a href="{% url 'user_app:signup_url' %}" style="color: #008080"> registration</a>.
			<br>You can <a href="{% url 'user_app:login_url' %}" style="color: #008080">login</a> if you have account already...
			</p>
		</div>

	</div> <!-- row end -->

{% endblock content %}